### ISSUE TITLE
How_To_Map_JIRA_Custom_Fields: how to add custom sprint ID?

### ISSUE THREAD

**Issue by Sly777** [testfairy/docs#370]
Hey all, Is there any way to add custom sprint ID on creation?
![image](https://user-images.githubusercontent.com/694940/65136899-a9826780-da08-11e9-9d10-b2d401dc9c33.png)

I can just see `dynamic value` option here but I tried every possible key in there with sprint ID (`"101"`, `101`, `[101]`, `{101}`, `{[101]}`, `{["101"]}`, `{attr.test||101}`) but nothing works.

**Comment by gmegidish** [comment]
Hey @Sly777 . We just fixed something related to array with autocompletes on JIRA. Can you please try again, and notify support@testfairy.com? Thank you.
