### ISSUE TITLE
[iOS] Slow in switching between tabs

### ISSUE THREAD

**Issue by weilong88** [testfairy/docs#450]
Hi,

I've noticed the slowness switching between tabs in Tab Bar Controller after moving from v1.19.9 to v.1.20 +.

**Comment by gmegidish** [comment]
Hey @weilong88, I'm sorry for the delay in replying here. If the problem is still there, please contact TestFairy support directly. There shouldn't have been any slow down, and we're here to help you debug. Thanks!
